### ISSUE TITLE
Implement audio teaser view tracking in n-tracking

### ISSUE THREAD

**Issue by pixelandpage** [Financial-Times/n-tracking#21]
Implement audio teaser view tracking in n-tracking as it's required by several FT applications. 

Example implementation from https://github.com/Financial-Times/next-search-page/pull/264
```oTracking.view.init({
	selector: '.o-teaser--audio',
	getContextData: (el) => {
		return {
			componentContentId: el.getAttribute('data-id'),
			component: 'teaser',
			type: 'audio',
			subtype: 'podcast'
		};
	}
});```

**Comment by i-like-robots** [comment]
I agree with the rationale, but I don't think should be as straightforward as copy and pasting it.

In order to ensure this package remains supportable we need to attach some extra information to this event:

- [ ] Which developers know about it?
- [ ] Who _owns_ it?
- [ ] Which tracking spec does this implement?
- [ ] Is there are a Chartio package associated with it?
- [ ] Is there a known expiry date? If not, can we add one?
