### ISSUE TITLE
Documentation: Add a README for each tracker.

### ISSUE THREAD

**Issue by adambraimbridge** [Financial-Times/n-tracking#33]
There's quite a lot of information that could be useful to anyone looking into https://github.com/Financial-Times/n-tracking/pull/32. That's too much to add to the project root's README. 

## Todo
 - [ ] Add a new README for src/client/trackers/real-user-monitoring-for-performance.js
 - [ ] Add READMEs for other trackers as appropriate
 - [ ] Link to those READMEs from the root README as appropriate.

**Comment by i-like-robots** [comment]
@kiyaGu Are you able to provide more information about copy tracking, or at least who is the ultimate stakeholder of this feature?

@adgad I have seen that attention time is part of the [quality reads definition](https://docs.google.com/document/d/1hkU31FTEQmsRCqVzQebEf--QCw4QncMtutYxdGw8QmE/edit) but how it is calculated is not specified. Do you happen to know 1) If this attention time code is used for this purpose? 2) If a spec for attention time exists?

**Comment by sjparkinson** [comment]
@chrisbrownuk would you be able to review what Spoor events and contexts are used to produce the Quality Reads metric? I suspect it is from the context of the `page:interaction` event, but there is no detail in the metrics definition at https://docs.google.com/document/d/1hkU31FTEQmsRCqVzQebEf--QCw4QncMtutYxdGw8QmE/edit.

**Comment by chrisbrownuk** [comment]
There are two events that are contributing to the attention time captured against each page view.   This then goes on to calculate the quality read flag.

The `page:interaction` event has the `context.context.attention.total` property and the `page:scrolldepth` event has the `context.meta.attention` property.  The maximum value from any of these events is recorded as the attention time for that page view.
Attention time was added to the scrolldepth event as the `page:interaction` event was not always generated.

There is also a deprecated `context.context.attention` property that is searched for but nothing is currently generating this.

**Comment by i-like-robots** [comment]
Thanks @chrisbrownuk for that extra information.

We don't currently have scroll depth accounted for in this repo but I have found where it was previously defined. It appears to create 4 markers on the page at 25% intervals and each time one is moved into view it triggers a `page:scrolldepth` event. Does this sound correct?

https://github.com/Financial-Times/n-ui/blob/4bb1ba6872d576a209938c2acffa0a546127ac01/components/n-ui/tracking/ft/events/scroll-depth.js 

Thank you for also pointing out the relationship between the two, this is something I was not aware of and I'll ensure it's preserved.

**Comment by chrisbrownuk** [comment]
@i-like-robots Yes, that's correct with regards to the `page:scrolldepth` event.  Also note that scrolling back up and down does not reissue the smaller scroll depth values.

Unfortunately I don't have any documentation regarding the implementation of these events.

**Comment by kiyaGu** [comment]
> @kiyaGu Are you able to provide more information about copy tracking, or at least who is the ultimate stakeholder of this feature?

I'm not sure who the ultimate stakeholder is but our current contact is Philippa Payne.
The way Prospector use the copy tracking data is that data platform team have a script that runs an SQL command against redshift (lighthouse data model) for identifying readers who have copied more than 100K characters and they export the result as a CSV file to an S3 bucket every day which Prospector ingest, enrich and then create these readers as lead in salesforce for sales team.
